version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      # Ignore major version updates for these actions
      - dependency-name: "actions/cache"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actions/configure-pages"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Mix
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10