name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.18.2'
            otp: '27.2'
          - elixir: '1.15.7'
            otp: '26.0'
          - elixir: '1.14.5'
            otp: '25.3'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo groupadd wireshark || true
        sudo apt-get install -y tcpdump tshark
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure wireshark-common
        sudo setcap cap_net_raw,cap_net_admin+eip $(which tcpdump)
        sudo setcap cap_net_raw,cap_net_admin+eip $(which dumpcap)
        sudo usermod -a -G wireshark $USER || true
        groups

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install mix dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Check formatting
      run: |
        ls -la
        mix format --check-formatted --dry-run

    - name: Run Credo
      run: mix credo --strict

    - name: Run tests with coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MIX_ENV: test
      run: |
        mix test
        mix coveralls.html

    - name: Run Dialyzer
      run: mix dialyzer

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report-${{ matrix.elixir }}
        path: cover
        if-no-files-found: error